\connect monopolydb;
CREATE SCHEMA monopoly;

create table if not exists game
(
    id      bigint generated by default as identity
        primary key,
    created timestamp
);

create table if not exists cell
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(255),
    game_id bigint not null
        constraint fk1ay567kp9m6tfnsyeexhl6bav
            references game
);

create table if not exists chip
(
    id      bigint generated by default as identity
        primary key,
    name    varchar(255),
    game_id bigint not null
        constraint fkhbegwmx5gv5pb4qs6piyimf8s
            references game
);
